# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desighn.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import datetime
import speech_recognition as  sr
import datefinder
import pyttsx3
from PyQt5.QtGui import QMovie
from PyQt5 import QtCore, QtGui, QtWidgets
# import  winsound



flags = QtCore.Qt.WindowFlags(QtCore.Qt.FramelessWindowHint)









class Ui_Form(object):


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920,1080)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1370,750))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/new1/layout.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(259, 50, 882, 310))
        self.label_1.setText("")
        self.label_1.setPixmap(QtGui.QPixmap(":/new1/animation.gif")) #

        """
        Here we are making the animation working
        """


        self.movie = QMovie(":/new1/animation.gif")
        # self.movie.frameChanged.connect(self.repaint)
        # self.movie.setCacheMode(QMovie.CacheAll)
        self.label_1.setMovie(self.movie)
        self.movie.start()

        """
        -----------------------------
        """






        self.label_1.setScaledContents(True)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Form)

        self.label_2.setGeometry(QtCore.QRect(100, 490, 180, 185))
        self.label_2.setText("")


        self.label_2.setPixmap(QtGui.QPixmap(":/new1/new.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(595, 472, 180, 210))
        self.label_3.setText("")

        self.label_3.setPixmap(QtGui.QPixmap(":/new1/WhatsApp Image 2020-08-13 at 10.12.45 PM.jpeg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")

        """
        LABEL 4 
        """


        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(1080, 470, 190, 212))
        self.label_4.setText("")


        self.label_4.setPixmap(QtGui.QPixmap(":/new1/91c218f3f7fc7a8d840ab5a344a7b0fc.gif"))


        """
        Here we are making the animation working
        """

        self.movie = QMovie(":/new1/91c218f3f7fc7a8d840ab5a344a7b0fc.gif")
        # self.movie.frameChanged.connect(self.repaint)
        # self.movie.setCacheMode(QMovie.CacheAll)
        self.label_4.setMovie(self.movie)
        self.movie.start()

        """
        ----------------------------------------
        """
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(345, 475, 184, 205))


        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/new1/dna.gif"))
        """
        Here we are making the animation working
        """

        self.movie = QMovie(":/new1/dna.gif")
        # self.movie.frameChanged.connect(self.repaint)
        # self.movie.setCacheMode(QMovie.CacheAll)
        self.label_5.setMovie(self.movie)
        self.movie.start()
        """
        ------------------------
        """

        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")



        """
         NEXT LABEL THAT IS LABEL 6
        """
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(840, 472, 180, 213))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/new1/original.gif"))

        """
         Here we are making the animation working
         """
        self.movie = QMovie(":/new1/original.gif")
        # self.movie.frameChanged.connect(self.repaint)
        # self.movie.setCacheMode(QMovie.CacheAll)
        self.label_6.setMovie(self.movie)
        self.movie.start()

        """
        ----------------------------------------
        """


        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")



        """
        NEW LABEL THAT MEANS LABEL 7
        """
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(346, 383, 120, 31))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/new1/exit - Copy.png"))

        """
        LOIC FOR WORKING THE LABEL AS A BUTTON
        """


        B1 =QtWidgets.QPushButton(Form)
        # b1.clicked.connect()
        B1.setGeometry(QtCore.QRect(346, 383, 120, 31))
        # B1.setPixmap(QtGui.QPixmap(":/new1/exit - Copy.png"))
        B1.setObjectName("compressed_button")
        B1.setText("Exit")


        # B1.setStyleSheet(":/new1/exit - Copy.png")
        B1.clicked.connect(sys.exit)

        """
        --------------------------------------------
        """



        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)






    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))




    # winsound.PlaySound("G:\\Git Tutorial\\Project Jarvis\\music\\binarySong.wav", winsound.SND_LOOP)


import rec_rc


if __name__ == "__main__":
    import sys


    app = QtWidgets.QApplication(sys.argv)

    Form = QtWidgets.QWidget()

    ui = Ui_Form()

    ui.setupUi(Form)

    Form.show()
    


    sys.exit(app.exec_())





